### ISSUE TITLE
Getting error while executing fastdup.py

### ISSUE THREAD

**Issue by ls-milkyway** [visualdatabase/fastdup#10]
Hi !
I am sort of newbie to python...

Installed fastdup successfully on ubuntu 20.04 by creating a separate environment with python 3.8
Activated the environment ....copied the code as mentioned in your website:
`import fastdup
fastdup.run(input_dir="/path/to/your/folder", work_dir='out')                            #main running function
fastdup.create_duplicates_gallery('out/similarity.csv', save_path='.')       #create a visual gallery of found duplicates
fastdup.create_outliers_gallery('out/outliers.csv',   save_path='.')       #create a visual gallery of anomalies
fastdup.create_components_gallery('out', save_path='.')                    #create visualiaiton of connected components`

in file fast.py but when I execute `python3 fastdup.py` I get error:

Traceback (most recent call last):
  File "fast.py", line 2, in <module>
    fastdup.run(input_dir="/home/rana/Fast-Duplicate/pics", work_dir='/home/rana/Fast-Duplicate/out')                            #main running function
AttributeError: module 'fastdup' has no attribute 'run'

FYI:
Fast-Duplicate is the folder inside which python environment was created and fastdup was installed successfully.
i have copied the  folder named pics inside Fast-Duplicate....&  created out folder there.
pics is the folder containing many images, all inside categorized folders.....say it has folders food, bicycle, bus etc containing many respective images.

**Comment by ls-milkyway** [comment]
ok figured it out ....silly mistake ...I was using `python3 fast.py` instead of `python3.8 fast.py`

**Comment by dbickson** [comment]
Hi @ls-milkyway  Good that you figure this out, keep us posted for any further issues!
