### ISSUE TITLE
fastdup run does not work on zip / tar files

### ISSUE THREAD

**Issue by Xnsam** [visualdatabase/fastdup#15]
Hi,

I was trying to use the fastdup https://visualdatabase.github.io/fastdup/#fastdup.run, as per the instructions mentioned in the link for zipped / tar compressed images.

but for some reason it does not work 
![image](https://user-images.githubusercontent.com/23662182/188669794-012de041-f7f2-425d-8886-d803a92c1031.png)

Please can anyone suggest.

fastdup == 0.137

**Comment by dbickson** [comment]
HI @Xnsam we would love to help. From some reasons some of the outputs are getting swallowed by jupyter notebook. Can you please run the following way and send us the output.
`python -c "import fastdup; fastdup.run(... ....)"`
and we will help debug what has gone wrong. Also don't forget to assign `work_dir='output'` where output is a new folder name that did not exist before.

**Comment by Xnsam** [comment]
> HI @Xnsam we would love to help. From some reasons some of the outputs are getting swallowed by jupyter notebook. Can you please run the following way and send us the output. `!python -c "import fastdup; fastdup.run('test_zip/data', turi_param='tar_only=1', work_dir='output', verbose=1)"` and we will help debug what has gone wrong. Also don't forget to assign `work_dir='output'` where output is a new folder name that did not exist before.

I tried, this is the output
![image](https://user-images.githubusercontent.com/23662182/188696140-76e0843e-2e92-4b08-8d7b-2dc1d7ad1040.png)

**Comment by dbickson** [comment]
Hi, please try the instructions here: https://github.com/visualdatabase/fastdup/blob/main/RUN.md#tar
You need to first run with run_mode=1, to extract the feature vectors from the tar files since we do not know how many files are inside. The second step is to run again with run_mode=2 to build the nearest neighbor model so you need to run it using the same work_dir.

**Comment by Xnsam** [comment]
This helps, thank you

**Comment by dbickson** [comment]
Hi @Xnsam I see your reopened the issue, let me know if you observed any problem?

**Comment by Xnsam** [comment]
No issue, its working with tar and zip compressed files
