### ISSUE TITLE
Fastdup cant be installed pip version<22

### ISSUE THREAD

**Issue by mburaksayici** [visualdatabase/fastdup#17]
I was trying to install fastdup into docker.

Fastdup cant be installed if pip version is not latest, or larger then 22.0. It says it couldn't find the package.
so pip install --upgrade pip was needed.

I think its worth mentioning this fix somewhere, that's the issue. Otherwise people that ll build in docker will spend 3 hours like me to find out whats going on.

**Comment by dbickson** [comment]
HI @mburaksayici apologies for the unclear documentation.
The correct way to work with docker is explained here: https://github.com/visualdatabase/fastdup/blob/main/INSTALL.md#docker namely you can have a preconfigured docker with everything installed in it.

The pip upgrade is mentioned in the pip section https://github.com/visualdatabase/fastdup/blob/main/INSTALL.md#pypi  and also in the main readme: 
```
# upgrade pip to its latest version
python3.XX -m pip install -U pip
# install fastdup
python3.XX -m pip install fastdup
```

**Comment by mburaksayici** [comment]
Oh sorry. I spent lots of time on this, as its little bit unexpected. Thabks for help !

**Comment by dbickson** [comment]
Apologies @mburaksayici , please sign up to our slack channel https://join.slack.com/t/visualdatabase/shared_invite/zt-19jaydbjn-lNDEDkgvSI1QwbTXSY6dlA and next time you are stuck reach out and we will help quickly.
Best
