### ISSUE TITLE
How to find wrong labels?

### ISSUE THREAD

**Issue by huiwen99** [visualdatabase/fastdup#2]
Thank you for the amazing tool! I noticed the section "Find wrong labels" in the README, but there was no corresponding function in the RUN.md. How should I find wrong labels, and is it possible for the tool to suggest the correct label?

**Comment by dbickson** [comment]
Thanks so much @huiwen99 for your kind words! 
In a nutshell what we did is first run fastdup to build an NN model. Then we clustered using fastdup connected components (see the output file `connected_components.csv` which is generated on default in each run). You can play with the connected component threshold to get more similar or less similar images are grouped together using the `turi_param='ccthreshold=0.XX'`. cchtreshold close to 1 will get you only duplicate images and lower cchtreshold will get you less similar images grouped together. 

Next, we join the connected components file based on the image id into the label files. 
Example component id file:

```
__id,component_id
0,662
1,1470
2,841
3,1307
4,1738
5,114
6,1037
7,65
```

Prepare a label file with the format
```
__id,label
0,dog
1,cat
2,horse
...
```

```python
import pandas as pd
comp = pd.read_csv('connected_components')
labels = pd.read_csv('labels')
joined = comp.join(labels, on='__id')
```

Now we looked at the components that have a small number of outlier labels, those mosts likely are wrong labels. 

```python
ret = joined.groupby(['component','label']).agg('count')
```

Let us know if you like to connect for a zoom demo we would love sharing what we got and learn more about your problem. We are actively collecting inputs from users to improve the next versions of `fastdup`.

**Comment by amiralush** [comment]
In addition the what @dbickson has written. You are also welcome to join our Slack channel: https://join.slack.com/t/visualdatabase/shared_invite/zt-19jaydbjn-lNDEDkgvSI1QwbTXSY6dlA as continue the conversation there.
