### ISSUE TITLE
Allow different backbones for bottleneck features

### ISSUE THREAD

**Issue by lwzhaojun** [visualdatabase/fastdup#21]
Does the program now support EfficientNet weighting as backbone? My model: (batch, channel, width, height )= (1802, 1, 62, 96).output_size=(1803,1280). Here's how I used it:

`fastdup.run('/home/datasets', work_dir='out', nearest_neighbors_k=478, model_path='efficientnetb1.ort', d=1280)
`
When I use the model, I get the following error, what parameters need to be adjusted in the source code to apply, can you give some suggestions?
`Found total 479 images to run on
Failed assertion false /home/ubuntu/visual_database/cxx/src/image_to_blob.h:222
Failed assertion false /home/ubuntu/visual_database/cxx/src/image_to_blob.h:222
free(): corrupted unsorted chunks
Segmentation fault (core dumped)`

**Comment by lwzhaojun** [comment]
In fact, the RGB image model has also been tried, and the same error will be reported. Here is my single-channel model.
[efficientb1.zip](https://github.com/visualdatabase/fastdup/files/9805786/efficientb1.zip)

The following is the three-channel model.
[efficientb1_3.zip](https://github.com/visualdatabase/fastdup/files/9805803/efficientb1_3.zip)
Please help me see it.

**Comment by dbickson** [comment]
hi @lwzhaojun. We have identified the source of the error that the expected image size is 96x62 while so far we support default image sizes of 224x224. Give us a couple of days so we could update the code to add non square image support.

**Comment by dbickson** [comment]
BTW I was not able to download the first zip file if you can send it again please. I was able to download the RGB model.

**Comment by lwzhaojun** [comment]
Thank you for your support. After I modified the RGB image size to 224x224×3, The following error occurred: 
`Failed assertion ptr[j] >= MIN_FEATURE_ALLOWED_VAL && ptr[j] < MAX_FEATURE_ALLOWED_VAL /home/ubuntu/visual_database/cxx/src/data_debug.hpp:354`
If you can, I hope you can help debug the 96×62×1. Below is the model of 96×62×1.
[efficientb1.zip](https://github.com/visualdatabase/fastdup/files/9816292/efficientb1.zip)
Below is the model of 224x224×3.
[efficientnet-224rgb.zip](https://github.com/visualdatabase/fastdup/files/9816295/efficientnet-224rgb.zip)

**Comment by lwzhaojun** [comment]
I'm sorry to verify it now, I just verified that the program can run whether it is an RGB model, a single-channel model, or a non square input. Thank you very much for your great support. 
Regarding normalization, we haven't normalized before, but I think normalization is still very important, and I will do a version of normalization recently, and I will have to ask you to support it at that time. 
By the way, did you only update to the pip library, not to the github source code? 
Finally, you can close the issue. Thanks again.

**Comment by dbickson** [comment]
hi @lwzhaojun we are glad to hear the update is working for you!
I believe it will be useful to add normalization, send me the normalization you need, we will add some way for the user to provide it. The changes we did were in our c++ engine which is not open source thus you did not see changes in the python side.
Best,
