### ISSUE TITLE
What is used as feature extractor? 

### ISSUE THREAD

**Issue by levan92** [visualdatabase/fastdup#7]
Hi, can I check what is used as your feature extractor?

**Comment by dbickson** [comment]
Hi @levan92 we use a proprietary feature extractor which we found to be both fast and gives accurate similarities for large variety of datasets. It is possible to support external models, for example CLIP is already supported. We are planning to release a demo notebook soon. Let us know if there are any features that are missing for your usecase?

**Comment by da2r-20** [comment]
@levan92, You can get both the model name, layers names and output layer name and dim from the onnx model which is included as part of the package
