### ISSUE TITLE
[Feature Request] - Allow different backbones for bottleneck features

### ISSUE THREAD

**Issue by lanalex** [visualdatabase/fastdup#9]
Can you add support for The Resnet50 backbone used in fast mask RCNN  on the CityScape dataset or the BDD100K dataset.

In the Detailed Run section, it says path to ONNX file **should not be used** so it seems that its not yet supported. 
I am not talking about full ability to add weights, but maybe some presets, of common weight backbones in different tasks (as a simpler interface to actually completely setting an onnx file) . So the API can be 

```
fastdup.run(input_dir="./tagged_sliced", work_dir='out', backbone = 'resnet.cityscape') 
```

**Comment by dbickson** [comment]
Hi @lanalex send us an onnx file of the model you like (should be compiled as [batch x channel x width x height ] and we will make sure it works for you.

**Comment by dbickson** [comment]
I will try to add support soon. Image channels are 3 right?

**Comment by dbickson** [comment]
HI @lanalex we have just release v. 0.119 for mac m1 which runs your onnx model, note that you have to provide model_path=<path to onnx model> as well as d=<output feature width>.
Here is an example of the c++ api:
<img width="1318" alt="Screen Shot 2022-07-27 at 21 28 58" src="https://user-images.githubusercontent.com/4495523/181346044-b8131321-eecd-4394-aa9c-4879bd1c4feb.png">
Let me know if you have another os?
